server:
  port: 8086

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/OpenJar?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "mappings"
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8181/realms/RecipeRealm
#          jwk-set-uri: http://localhost:8181/realms/RecipeRealm/protocol/openid-connect/certs